---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  log_level: <%= ENV['CHEF_LOG_LEVEL'] || 'auto' %>

platforms:
  - name: centos-7.1
    driver:
      box: centos-71
      box_url: https://deploy.gmti.gbahn.net/Images/centos7/vagrant/centos71-cloud-1.0.0.box
      network:
        - ["forwarded_port", {guest: 80, host: 8080}]

suites:
  - name: default
    data_bags_path: test/integration/data_bags
    run_list:
      - recipe[test-variables]
      - recipe[gd-test-helper::default]
      - recipe[sauceconnect::default]
    attributes:
      sauceconnect:
        configuration_files:
          - development-sauceconnect.conf
        s3-config-bucket: 'gdp-testing/sauceconnect'
        config-from-s3: true
        config-dir: 'config'
        s3:
          test_config: true
          aws_key: <%= ENV['CHEF_SAUCECONNECT_AWS_KEY'] %>
          aws_secret: <%= ENV['CHEF_SAUCECONNECT_AWS_SECRET_KEY'] %>
    scalr:
        check-command: "echo scalr"
        environment-check-command: "echo Testing"
        farmname-check-command: "echo test-farm"
    chef_client:
      config:
        log_level: ":debug"
